# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-5c4ff8a1-c35d-4244-8a36-f81bc112f164";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5c4ff8a1-c35d-4244-8a36-f81bc112f164" = {
    device = "/dev/disk/by-uuid/5c4ff8a1-c35d-4244-8a36-f81bc112f164";
    # Let the weekly fstrim service notify the NVMe about unused blocks.
    allowDiscards = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3810-C777";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-82faf233-904a-4f35-8b07-47c8b1cad332"; }
  ];
  boot.initrd.luks.devices."luks-82faf233-904a-4f35-8b07-47c8b1cad332" = {
    device = "/dev/disk/by-uuid/82faf233-904a-4f35-8b07-47c8b1cad332";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
