# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0c8d6ba1-e368-4c9f-b34d-a818b272ba58";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0c8d6ba1-e368-4c9f-b34d-a818b272ba58".device = "/dev/disk/by-uuid/0c8d6ba1-e368-4c9f-b34d-a818b272ba58";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0242-AE00";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    { device = "/dev/mapper/luks-0432ea0c-d8a2-4750-9cb3-ce3229f53978"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
