# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-022361ea-0a9d-4a0e-9375-ed4c38460224";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-022361ea-0a9d-4a0e-9375-ed4c38460224".device = "/dev/disk/by-uuid/022361ea-0a9d-4a0e-9375-ed4c38460224";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A963-2ADF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    { device = "/dev/mapper/luks-86adca68-ce6c-40cf-a0be-cf1432f342cd"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
