(deftheme rose-pine-moon
  "Rose Pine Moon theme tuned for transparent terminal backgrounds.")

(let ((base "#232136")
      (surface "#2a273f")
      (overlay "#393552")
      (muted "#6e6a86")
      (subtle "#908caa")
      (text "#e0def4")
      (love "#eb6f92")
      (gold "#f6c177")
      (rose "#ea9a97")
      (pine "#3e8fb0")
      (foam "#9ccfd8")
      (iris "#c4a7e7")
      (green "#95b1ac"))
  (custom-theme-set-faces
   'rose-pine-moon
   `(default ((t (:background ,base :foreground ,text))))
   `(cursor ((t (:background ,rose))))
   `(fringe ((t (:background ,base :foreground ,muted))))
   `(vertical-border ((t (:foreground ,overlay))))
   `(minibuffer-prompt ((t (:foreground ,iris :weight bold))))
   `(region ((t (:background ,overlay :foreground ,text))))
   `(secondary-selection ((t (:background ,surface :foreground ,text))))
   `(highlight ((t (:background ,surface))))
   `(hl-line ((t (:background ,surface))))
   `(line-number ((t (:background ,base :foreground ,muted))))
   `(line-number-current-line ((t (:background ,base :foreground ,gold :weight bold))))
   `(mode-line ((t (:background ,overlay :foreground ,text :box nil))))
   `(mode-line-inactive ((t (:background ,surface :foreground ,subtle :box nil))))
   `(header-line ((t (:background ,surface :foreground ,text :box nil))))
   `(isearch ((t (:background ,gold :foreground ,base :weight bold))))
   `(isearch-fail ((t (:background ,love :foreground ,base :weight bold))))
   `(lazy-highlight ((t (:background ,overlay :foreground ,gold))))
   `(match ((t (:background ,overlay :foreground ,foam :weight bold))))
   `(show-paren-match ((t (:background ,overlay :foreground ,gold :weight bold))))
   `(show-paren-mismatch ((t (:background ,love :foreground ,base :weight bold))))
   `(link ((t (:foreground ,foam :underline t))))
   `(shadow ((t (:foreground ,muted))))
   `(error ((t (:foreground ,love :weight bold))))
   `(warning ((t (:foreground ,gold :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   ;; ANSI colors used by `eat', compilation buffers, and shell output.
   ;; Keeping these in the theme prevents terminal applications from falling
   ;; back to Emacs's saturated default red/green/blue palette.
   `(ansi-color-black ((t (:foreground ,overlay :background ,overlay))))
   `(ansi-color-red ((t (:foreground ,love :background ,love))))
   `(ansi-color-green ((t (:foreground ,pine :background ,pine))))
   `(ansi-color-yellow ((t (:foreground ,gold :background ,gold))))
   `(ansi-color-blue ((t (:foreground ,foam :background ,foam))))
   `(ansi-color-magenta ((t (:foreground ,iris :background ,iris))))
   `(ansi-color-cyan ((t (:foreground ,rose :background ,rose))))
   `(ansi-color-white ((t (:foreground ,text :background ,text))))
   `(ansi-color-bright-black ((t (:foreground ,muted :background ,muted))))
   `(ansi-color-bright-red ((t (:foreground ,love :background ,love))))
   `(ansi-color-bright-green ((t (:foreground ,pine :background ,pine))))
   `(ansi-color-bright-yellow ((t (:foreground ,gold :background ,gold))))
   `(ansi-color-bright-blue ((t (:foreground ,foam :background ,foam))))
   `(ansi-color-bright-magenta ((t (:foreground ,iris :background ,iris))))
   `(ansi-color-bright-cyan ((t (:foreground ,rose :background ,rose))))
   `(ansi-color-bright-white ((t (:foreground ,text :background ,text))))
   `(font-lock-builtin-face ((t (:foreground ,foam))))
   `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,rose))))
   `(font-lock-doc-face ((t (:foreground ,subtle))))
   `(font-lock-function-name-face ((t (:foreground ,pine :weight semi-bold))))
   `(font-lock-keyword-face ((t (:foreground ,iris :weight semi-bold))))
   `(font-lock-negation-char-face ((t (:foreground ,love))))
   `(font-lock-preprocessor-face ((t (:foreground ,gold))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,gold))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,iris))))
   `(font-lock-string-face ((t (:foreground ,gold))))
   `(font-lock-type-face ((t (:foreground ,foam))))
   `(font-lock-variable-name-face ((t (:foreground ,text))))
   `(font-lock-warning-face ((t (:foreground ,love :weight bold))))
   `(completions-first-difference ((t (:foreground ,gold :weight bold))))
   `(vertico-current ((t (:background ,overlay :foreground ,text))))
   `(corfu-default ((t (:background ,surface :foreground ,text))))
   `(corfu-current ((t (:background ,overlay :foreground ,text))))
   `(corfu-bar ((t (:background ,iris))))
   `(org-document-title ((t (:foreground ,iris :weight bold :height 1.3))))
   `(org-document-info ((t (:foreground ,subtle))))
   `(org-document-info-keyword ((t (:foreground ,muted))))
   `(org-level-1 ((t (:foreground ,iris :weight bold :height 1.15))))
   `(org-level-2 ((t (:foreground ,foam :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,gold :weight bold :height 1.05))))
   `(org-level-4 ((t (:foreground ,rose :weight bold))))
   `(org-level-5 ((t (:foreground ,green :weight bold))))
   `(org-level-6 ((t (:foreground ,subtle :weight bold))))
   `(org-level-7 ((t (:foreground ,pine :weight bold))))
   `(org-level-8 ((t (:foreground ,muted :weight bold))))
   `(org-todo ((t (:foreground ,love :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))
   `(org-headline-done ((t (:foreground ,muted))))
   `(org-checkbox ((t (:foreground ,gold :weight bold))))
   `(org-block ((t (:background ,surface :extend t))))
   `(org-block-begin-line ((t (:background ,surface :foreground ,muted :slant italic :extend t))))
   `(org-block-end-line ((t (:background ,surface :foreground ,muted :slant italic :extend t))))
   `(org-quote ((t (:background ,surface :foreground ,subtle :slant italic :extend t))))
   `(org-verse ((t (:background ,surface :foreground ,subtle :slant italic :extend t))))
   `(org-code ((t (:foreground ,gold))))
   `(org-verbatim ((t (:foreground ,rose))))
   `(org-table ((t (:foreground ,foam))))
   `(org-link ((t (:foreground ,foam :underline t))))
   `(org-date ((t (:foreground ,subtle :underline t))))
   `(org-tag ((t (:foreground ,muted :slant italic :weight normal))))
   `(org-special-keyword ((t (:foreground ,muted))))
   `(org-drawer ((t (:foreground ,muted))))
   `(org-meta-line ((t (:foreground ,muted :slant italic))))
   `(org-ellipsis ((t (:foreground ,muted :underline nil))))
   `(org-modern-label ((t (:foreground ,text))))
   `(org-modern-tag ((t (:background ,overlay :foreground ,subtle))))
   `(org-modern-todo ((t (:background ,love :foreground ,base :weight bold))))
   `(org-modern-done ((t (:background ,overlay :foreground ,green :weight bold))))
   `(org-modern-date-active ((t (:background ,overlay :foreground ,text))))
   `(org-modern-date-inactive ((t (:background ,surface :foreground ,muted))))
   `(org-modern-time-active ((t (:background ,iris :foreground ,base))))
   `(org-modern-time-inactive ((t (:background ,overlay :foreground ,muted))))
   `(doom-modeline-bar ((t (:background ,iris))))
   `(doom-modeline-buffer-file ((t (:foreground ,text :weight bold))))
   `(doom-modeline-buffer-modified ((t (:foreground ,gold :weight bold))))))

(provide-theme 'rose-pine-moon)
