[backdrop]
blur_intensity = 0.0
enabled = true
tint_intensity = 0.0

[bar.default]
center = [ "media", "clock" ]
end = [
    "tray",
    "clipboard",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "wallpaper",
    "notifications"
]
font_family = "Moralerspace Radon HW"
margin_ends = 0
radius = 0
start = [ "launcher", "workspaces" ]

[calendar]
enabled = true

    [calendar.account.personal_google]
    color = "primary"
    name = "rei"
    type = "google"

[control_center.calendar]
show_events_card = false
show_week_numbers = true

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002", "desktop-widget-0000000000000003", "desktop-widget-0000000000000004" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 96.0
    box_width = 144.0
    cx = 2152.0
    cy = 112.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        timezone = "Europe/Zurich"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 2164.0
    cy = 384.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "calendar"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 0.0
    box_width = 0.0
    cx = 1956.0
    cy = 112.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "weather"

[location]
address = "Tokyo/Tokyo"
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd]
enabled = false

    [osd.kinds]
    keyboard_layout = false

[shell]
avatar_path = "/home/rei/Pictures/self/night.jpg"
font_family = "Monaspace Radon Var"

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true

[theme]
builtin = "Rosé Pine"
mode = "light"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/rei/Pictures/wallpapers"

    [wallpaper.automation]
    enabled = true
    interval_seconds = 900

    [wallpaper.default]
    path = "/home/rei/Pictures/wallpapers/miku.JPG"

    [wallpaper.last]
    path = "/home/rei/Pictures/wallpapers/miku.JPG"

    [wallpaper.monitors.DP-1]
    path = "/home/rei/Pictures/wallpapers/miku.JPG"

[widget.clock]
format = "{:%b %d %a %H:%M}"

[widget.volume.actions]
scroll_down = "volume-up 2"
scroll_up = "volume-down 2"
